# Generated by Django 4.0.3 on 2022-04-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0002_alter_fooditem_flavors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='quantity',
        ),
    ]
