# Generated by Django 4.0.3 on 2022-04-10 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0006_alter_fooditem_quantity'),
        ('order', '0003_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='food_items.fooditem'),
        ),
    ]
